version: "3"

services:

  nginx:
    container_name: "loopygen.nginx"
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - react
    ports:
      - "8080:80"
    volumes:
      - ./dockerfiles/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      loopygen:
        ipv4_address: 172.101.0.100

  react:
    container_name: "loopygen.react"
    build: ./react
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/usr/src/common:rw
    networks:
      loopygen:
        ipv4_address: 172.101.0.110

  python:
    container_name: "loopygen.python"
    build: .
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/app:rw
    networks:
      loopygen:
        ipv4_address: 172.101.0.115

networks:
  loopygen:
    name: loopygen
    ipam:
      config:
        - subnet: 172.101.0.0/24
