version: "3"

services:

  nginx:
    container_name: "loopygen.nginx"
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./dockerfiles/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      loopygen:
        ipv4_address: 172.101.0.100

  react:
    container_name: "loopygen.react"
    build: ./react
    user: ${UID}:${GID}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/usr/src/server:rw
    networks:
      loopygen:
        ipv4_address: 172.101.0.110

  python:
    container_name: "loopygen.python"
    build: .
    user: ${UID}:${GID}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/var/www/html:rw
    networks:
      loopygen:
        ipv4_address: 172.101.0.115

networks:
  loopygen:
    name: loopygen
    ipam:
      config:
        - subnet: 172.101.0.0/24
