version: "3"

services:

  loopygen:
    container_name: "loopygen"
    image: "sk33z3r/loopygen:${HUB_TAG}"
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./collections:/var/www/html/collections:rw