name: Docker Image CI

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - v*.*.*

env:
  HUB_TAG: "ci"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker-compose build
