name: Docker Registry CI

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  HUB_TAG: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sk33z3r/loopygen:${{ env.HUB_TAG }}, sk33z3r/loopygen:latest
