name: Docker Image CI

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - v*.*.*

env:
  HUB_TAG: "ci"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Build the GUI image
        run: docker-compose build
      -
        name: Build the CLI image
        run: docker build -t sk33z3r/loopygen-cli:${{ env.HUB_TAG }} -f Dockerfile.cli .
